#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates Sources/Mixi2/Generated/EventMessageExtensions.swift from the generated event
# protobuf file. Parses the OneOf_Body enum inside the Event type and emits
# Mixi2EventMessage conformances for every non-ping event message type.
#
# Run via: make generate

INPUT  = "Sources/Mixi2GRPC/Generated/social_mixi_application_model_v1_event.pb.swift"
OUTPUT = "Sources/Mixi2/Generated/EventMessageExtensions.swift"

content = File.read(INPUT)

# Extract the OneOf_Body enum block
oneof_block = content[/public enum OneOf_Body.*?\{(.*?)\n  \}/m, 1]
abort "ERROR: Could not find OneOf_Body enum in #{INPUT}" unless oneof_block

# Parse each `case label(TypeName)` line
cases = oneof_block.scan(/^\s*case (\w+)\((\w+)\)/)
abort "ERROR: No cases found in OneOf_Body" if cases.empty?

# Skip ping — it is filtered out by EventStream and is not a user-facing event
cases.reject! { |label, _| label == "pingEvent" }

lines = []
lines << "// DO NOT EDIT — generated by scripts/generate_event_message_extensions.rb"
lines << "// Run `make generate` to regenerate."
lines << ""
lines << "import Mixi2GRPC"
lines << ""

cases.each do |case_label, type_name|
  lines << "@available(macOS 15.0, iOS 18.0, *)"
  lines << "extension #{type_name}: Mixi2EventMessage {"
  lines << "    public static func extract(from event: Mixi2Event) -> Self? {"
  lines << "        guard case .#{case_label}(let e) = event.body else { return nil }"
  lines << "        return e"
  lines << "    }"
  lines << "}"
  lines << ""
end

File.write(OUTPUT, lines.join("\n"))

names = cases.map { |_, t| t }.join(", ")
puts "Generated #{OUTPUT} — #{cases.length} event message type(s): #{names}"
